version: '3'

services:

  php:
    image: rania1993/php:latest
    container_name: "site_web2"
    ports:
      - 8082:80
    restart: always
    volumes:
      - ./raniasite:/var/www/html/
    links:
      - db
  db:
    image: mysql:5.5
    container_name: "site_mysql"
    volumes:
      - ./dbsql:/home
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raniasite
    ports: 
      - 3360:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "site_pma"
    depends_on:
      - db
    ports:   
      - 8083:80
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root

volumes:
  dbsql: {}
  raniasite: {}

