version: '3'

services:

  php:
    build: .
    container_name: "deptest_web"
    ports:
      - 8087:80
    restart: always
    volumes:
      - ./raniasite:/var/www/html/
    links:
      - db
  db:
    image: mysql:5.5
    container_name: "deptest_mysql"
    volumes:
      - ./dbsql/raniasite.sql:docker-entrypoint-initdb.d/raniasite.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deptest
    ports: 
      - 3362:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "site_pma"
    depends_on:
      - db
    ports:   
      - 8085:80
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root

volumes:
  dbsql: {}
  raniasite: {}

